GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbWVzaSIsImlkIjoiNjJjZDIyY2QxMjU5YWQwNDcyOTNiNzg4IiwiaWF0IjoxNjU3NjEzODE4fQ.BLkvcfzfa6V4__nQxvA9mPJYeNIHxl_C3GiONJPjFvg

{
    "title": "user extractor test",
    "author": "me",
    "url": "www.sample.com",
    "likes": 89
}

###

GET http://localhost:3003/unknown/end/point/

###

PUT http://localhost:3003/api/blogs/62cd207e39917fa73798a5ca HTTP/1.1
content-type: application/json

{
    "title": "Example Content",
    "author": "me",
    "url": "https://www.example.com/",
    "likes": 16
}

###

DELETE http://localhost:3003/api/blogs/62cd4751fe2d9dadfbbc87d1 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbWVzaSIsImlkIjoiNjJjZDIyY2QxMjU5YWQwNDcyOTNiNzg4IiwiaWF0IjoxNjU3NjEzODE4fQ.BLkvcfzfa6V4__nQxvA9mPJYeNIHxl_C3GiONJPjFvg

###

POST http://localhost:3003/api/blogs/62dd0436d0f8ea9c5b84653b/comments HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbWVzaSIsImlkIjoiNjJjZDIyY2QxMjU5YWQwNDcyOTNiNzg4IiwiaWF0IjoxNjU3NjEzODE4fQ.BLkvcfzfa6V4__nQxvA9mPJYeNIHxl_C3GiONJPjFvg

{
    "comment": "another one"
}