GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/32505227

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Miss Testing Purposes",
  "number": "041-9483575"
}

###

GET http://localhost:3001/unknown/end/point/

###

DELETE http://localhost:3001/api/persons/62c7bbab2a6c827ea4ef9dda

###

PUT http://localhost:3001/api/persons/62c778538b7097455a33ae90 HTTP/1.1
content-type: application/json

{
  "name": "Mi",
  "number": "041-9483575"
}
