GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "new check with user",
    "author": "me",
    "url": "www.sample.com",
    "likes": 34,
    "userId": "62cd22cd1259ad047293b788"
}

###

GET http://localhost:3003/unknown/end/point/

###

PUT http://localhost:3003/api/blogs/62c8e907bc5ba9550035ebc7 HTTP/1.1
content-type: application/json

{
    "title": "test",
    "author": "me",
    "url": "www.example.com/blog",
    "likes": 16
}