GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "test3",
    "author": "me",
    "url": "www.sample.com",
    "likes": 32
}

###

GET http://localhost:3003/unknown/end/point/

###

PUT http://localhost:3003/api/blogs/62c4fd8029aca69dbdf3c5aa HTTP/1.1
content-type: application/json

{
    "title": "test",
    "author": "me",
    "url": "www.example.com/blog",
    "likes": 15
}